### ISSUE TITLE
Route Validation

### ISSUE THREAD

**Issue by Yourstruggle11** [Rajangrg/React-Ecommerce-Template#21]
# Report Bug

# There is no route validation.

# If a user logs out and then goes to / home he is being given access to the home page again which should not be happen. instead of that he/she should be sent back to the login page

**Comment by Rajangrg** [comment]
Hi, 

As this template is used for both the user/admin there is no need for route validation. The user should be able to see /home page despite the status (login/logout). The only difference is Admin can login to upload the product whereas normal user can't.

Thanks.
